### ISSUE TITLE
Save Duration For Clip Audio Bug

### ISSUE THREAD

**Issue by YaBoyRija** [GeekyEggo/SoundDeck#101]
No matter which option under the duration section I choose, it seems to always save a clip that is 2 minutes long. Could I get some help as to why this may be?

**Comment by GeekyEggo** [comment]
Hey @YaBoyRija, this is odd behaviour; I’m sorry you’re experiencing problems with things. Could I ask you to upload the logs file so I can see if that indicates any problems. They can be found on your local machine at:
`%appdata%\Elgato\StreamDeck\Plugins\com.geekyeggo.sounddeck.sdPlugin\logs`

**Comment by YaBoyRija** [comment]
Sure @GeekyEggo I believe this is it.

[SoundDeck.log](https://github.com/GeekyEggo/SoundDeck/files/10363313/SoundDeck.log)

**Comment by GeekyEggo** [comment]
Hey @YaBoyRija, apologies for my delayed response. The "Clip Audio" action has recently been improved, and should _hopefully_ resolve the issue you were having. The [latest beta (v3.10.0)](https://github.com/GeekyEggo/SoundDeck/raw/main/dist/com.geekyeggo.sounddeck.streamDeckPlugin) includes fixes and new durations for the clip audio actions. To ensure all settings are specified, my recommendation would be to create a new "Clip Audio" action after installing the beta.

I'm going to close this ticket for now in the hope that everything is okay, but if you have any problems, please feel free to post here, and we can continue the conversation! 😄
