### ISSUE TITLE
playing clip through my mic?

### ISSUE THREAD

**Issue by deckhaver** [GeekyEggo/SoundDeck#105]
sorry if this is the wrong place to ask but how do i go about playing a clip i have recorded through my mic so other people would be able to hear it too?

**Comment by GeekyEggo** [comment]
Hey @deckhaver, the Stream Deck community Discord is a great place for questions such as this, however I'll do my best to help. To achieve this you'll need to be able to "route audio"; there are a couple of ways to do this based on your setup. Here are some great resources to get started:
- [Route audio using Wave Link](https://streamdecklabs.com/elgato-soundboard-sfx-to-discord/)
- [Route audio using VoiceMeeter](https://streamdecklabs.com/%f0%9f%93%84-play-stream-deck-soundboard-sounds-on-discord/)

**Comment by deckhaver** [comment]
thank you so much for the fast response, i will try this now
