### ISSUE TITLE
previous issue with skipping audio

### ISSUE THREAD

**Issue by deckhaver** [GeekyEggo/SoundDeck#106]
the sound clips i record with sound deck are weirdly skipping forward i have tried changing the capture device but havent nailed the issue yet

**Comment by deckhaver** [comment]
even when i take a sample of my voice, when playing it back it is skipping and jumping ahead

**Comment by GeekyEggo** [comment]
Hey @deckhaver, in your previous #104, you mentioned you were able to fix things; what changes did you make?

**Comment by deckhaver** [comment]
i literally just changed the capture device but it only worked for one clip and then returned to skipping and jumping
could it be due to me having not enough space on my pc?

**Comment by deckhaver** [comment]
@GeekyEggo i appreciate your time with trying to help me :)

**Comment by deckhaver** [comment]
if it is a sfx file or something along those lines that i have imported, the issue does not happen

**Comment by GeekyEggo** [comment]
> could it be due to me having not enough space on my pc?

If you're experiencing existing disk space issues, this could definitely contribute to saving audio clips.

Here are a some things to try that might help to mitigate the problem.
- Try clipping with, and then without, "Encode to MP3" checked.
- Try the "Record Audio" action.
  - If this fails, it could indicate a problem with Sound Deck.
- Attempt to record the device in another application, e.g. Audacity
  - If this fails, it could indicate a problem with the audio device.

**Comment by GeekyEggo** [comment]
As there hasn't been any update on this, I'm going to close it for now, but I'll be happy to continue the conversation should you require any further help.
