### ISSUE TITLE
Support for Stream Deck + Dials

### ISSUE THREAD

**Issue by drewgourley** [GeekyEggo/SoundDeck#107]
Would like to use this plugin's device-level volume control with the Stream Deck + dials.

**Comment by GeekyEggo** [comment]
Hey @drewgourley, great news, there is an early beta for Sound Deck that adds some support for Stream Deck+, including device volume! It can be [downloaded directly from here](https://github.com/GeekyEggo/SoundDeck/raw/sd-plus/dist/com.geekyeggo.sounddeck.streamDeckPlugin). 

If you encounter any problems, or have any feedback, please let me know.

**Comment by drewgourley** [comment]
Holy shit this is sick! I appreciate your work so much, I just got this
thing (The Stream Deck +) and your plugin makes it so much better. I felt
bad because two seconds after I submitted this issue, I read another
comment you made on another issue that said you were working on this.

Anyway, thanks again!
-Drew

**Comment by GeekyEggo** [comment]
Thank you for the kind words! It’s always nice to hear when someone has found a use for Sound Deck. 😄

_p.s. I should probably go through other issues and update them with the latest beta, thank you, lol._
