### ISSUE TITLE
cant clip sound

### ISSUE THREAD

**Issue by Toastypaws** [GeekyEggo/SoundDeck#111]
when I try to clip the sound it doesn't work it has a yellow triangle I have the sound set as my headphones,, but it still doesn't work

**Comment by GeekyEggo** [comment]
Hey @Toastypaws; thankfully the "Clip Audio" has recently been updated in the [latest beta (v3.10.0)](https://github.com/GeekyEggo/SoundDeck/raw/main/dist/com.geekyeggo.sounddeck.streamDeckPlugin). Could I ask you to try with this version, ensuring the "Output Path" and "Duration" are specified in the settings window.

**Comment by Toastypaws** [comment]
hi I installed the version you gave me and it still wont work. it still has the yellow triangle

**Comment by GeekyEggo** [comment]
No problems; to help diagnose what might be causing this, could I grab the following details:
- Windows version?
- .NET Framework version? _(if unsure, [download and install](https://dotnet.microsoft.com/en-us/download/dotnet-framework) version 4.8 from Microsoft)_
- Stream Deck version?
- Screenshot of “Clip Audio” settings.
- Sound Deck logs files, located locally at `%appdata%\Elgato\StreamDeck\Plugins\com.geekyeggo.sounddeck.sdPlugin\logs`

**Comment by Toastypaws** [comment]
this only happens when I select a speaker or headphone as a capture device

**Comment by Toastypaws** [comment]
Windows Version: 22H2
.NET Framework version: 4.8 or later
Stream Deck version: 1.00.003
Screenshot of “Clip Audio” settings:
![image](https://user-images.githubusercontent.com/98718483/215360243-6577da6d-9deb-42de-9d9e-83d61236e03a.png)
Sound Deck logs file:
[SoundDeck.log](https://github.com/GeekyEggo/SoundDeck/files/10531063/SoundDeck.log)

**Comment by GeekyEggo** [comment]
From the logs, the error code appears to be `0x88890008`, which indicates there may be a misconfiguration with the audio device’s chosen format. To find out what it currently is, and what formats are available…
1. Press `Windows Key` + `R`
2. Enter `mmsys.cpl` and press enter to open the audio devices.
3. Right click a device you can’t record, and select “Properties”.
4. Select the “Advanced” tab.

What format is selected, and what formats are available?

**Comment by Toastypaws** [comment]
I can't record on any device from my headphones or speakers

but 24 bit is selected

**Comment by GeekyEggo** [comment]
What other formats are available?

**Comment by Toastypaws** [comment]
![image](https://user-images.githubusercontent.com/98718483/215361468-db9e21e7-e9f1-4f40-b260-fcc9fa48b502.png)

**Comment by GeekyEggo** [comment]
Do you have any “Enhancements” enabled for the device? If so, could you try:
1. Disabling them.
2. Exiting Stream Deck fully.
3. Opening Stream Deck, and try clipping.

**Comment by Toastypaws** [comment]
![image](https://user-images.githubusercontent.com/98718483/215362052-33be9067-e1f0-4161-b97b-c4ee6bd3862e.png)

**Comment by Toastypaws** [comment]
wait now it works

**Comment by GeekyEggo** [comment]
With enhancements disabled, it works? 🤞
