### ISSUE TITLE
Repeat Sound every X seconds

### ISSUE THREAD

**Issue by wmdkjozuercher** [GeekyEggo/SoundDeck#115]
Hi,

I use the Streamdeck for atmospheric sounds in our D&D Games. 
Would it be possible to add a repeat Sound Logic like here: https://tabletopaudio.com/darkforest_sp.html

you can click a time icon and let play thunder every X seconds.

BR,
Ole

**Comment by GeekyEggo** [comment]
Hey @wmdkjozuercher, this is an interesting idea! At the moment there's no concept of repeating a sound clip every x seconds. One option to achieve what you're looking for would be to amend the audio file and add an empty few seconds to the audio file. Within Sound Deck, you can then use the "Loop / Stop" option to continually play the audio file.
