### ISSUE TITLE
Suggestion: Keep Sampler audio length the same or Specific length

### ISSUE THREAD

**Issue by gelatinguy** [GeekyEggo/SoundDeck#117]
Hi, I like the Sampler, which allows me to loop a sample of audio. Perhaps this isn't the intended use for this plugin, but if it's meant to be used ever for making quick music samples, I think there needs to be an option to stick to the exact same length of time. Let me give an example.

- Let's say I record a loop of myself saying, "boots and cats and boots and cats." We'll say that file happens to be 1.1 seconds long.
- With that first sound now playing and looping, I record another loop sampler, and I record myself saying, "1 2 3 4." I let go of the button as precisely as I can, but that file is 1.07 seconds long.
- If I try to play the second sample, as the first one is still playing, they will never match up and it will sound awful after a couple seconds.

I would like a way to sync these up so they only play and loop at the same time as each other. One solution I suggest is to have a metronome that I can set and label it 'Tempo A', then set the sample toggle to match that 'Tempo A'. This way, if I record another sample to that metronome tempo, it will either be exactly the same length, or twice the length if I am close to that (or 3 times or 4 times).

This is probably out of the scope for this Sound Deck, but with the ability to record samples that loop, there has to be some sort of maintaining tempo and synced looping.

**Comment by GeekyEggo** [comment]
Hey @gelatinguy, thanks so much for taking the time to post a detailed and well thought-out request, it's greatly appreciated. 🙌

When originally creating the "Sampler" action, I had anticipated expanding on it further, and often suspected it could evolve _beyond_ Sound Deck, possibly as it's own plug-in. There is so much potential for a sampler action / plug-in within Stream Deck, and I've often toyed with the idea of creating a fully fledge "Loop Pedal" plug-in... although my lack of knowing how they work could make this a little challenging. 😅 I do like the idea of having a metronome as well, as that could greatly aide with timings.

At the moment, I don't foresee this becoming a feature within Sound Deck, but instead would love to see it as a standalone, dedicated plug-in. With that in mind, I'm going to mark this issue as "Close as not planned", but I will make a note of this issue to reference it, should creating that plug-in ever come to fruition (I personally hope it does).

**Comment by gelatinguy** [comment]
Thank you for the reply! I totally understand about the scope of the project. I hope to see more from you in the future, and keep up the great work!
