### ISSUE TITLE
Select a microphone on the Sampler Playback device

### ISSUE THREAD

**Issue by CarlinhosQuintieri** [GeekyEggo/SoundDeck#118]
I can't use the Sampler option to record audio from the discord for example e and then play it on my microphone

**Comment by GeekyEggo** [comment]
Hey @CarlinhosQuintieri, standard recording devices (e.g. microphones) aren’t able to playback audio. To achieve this, you’ll need additional software or hardware, with some configuration. Here are some options;
- [Software and Hardware (WaveLink)](https://streamdecklabs.com/elgato-soundboard-wave-link-sfx-to-discord/)
- [Software only (VoiceMeeter)](https://streamdecklabs.com/%F0%9F%93%84-play-stream-deck-soundboard-sounds-on-discord/)
