### ISSUE TITLE
Allow the Clip Audio to clip custom durations

### ISSUE THREAD

**Issue by CarlinhosQuintieri** [GeekyEggo/SoundDeck#119]
I think 15 seconds it too big for something I just head and want to clip, if i could use custom values like 5 seconds or 2 seconds it would be nicer

**Comment by GeekyEggo** [comment]
Hey @CarlinhosQuintieri, good suggestion. I’m tracking all changes of the clip action as part of #97, and although there haven’t been any changes yet, keep an eye there for anything upcoming. This will be included there 👍
