### ISSUE TITLE
"Play Audio" function not working after update

### ISSUE THREAD

**Issue by WhatIsGetHub** [GeekyEggo/SoundDeck#120]
Hello, 
First of all I want to thank you for the great addon.

In regards to my problem, I updated the software for stream deck ~1 month ago & all of sudden the new "Play Audio" function that I add cannot be played, while the older ones before I updated still can be played.

Any Idea what could be causing the problem ?

**Comment by GeekyEggo** [comment]
Hey @WhatIsGetHub, to help find the route of the problem, I'll need to gather some more information;
- What types of files are you attempting to play? e.g. MP3, WAV, etc.
- Can you play the files okay in other applications, e.g. Audacity.
- Have you updated Windows recently? Sadly, Windows has a habit of reseting audio device identifiers, so you might need to re-select the audio device in the action's settings.

**Comment by WhatIsGetHub** [comment]
Sure no problem.

I am playing MP3 format files, Files can be played on other applications without any problem. And no I haven't updated Windows recently, but after updating Stream Deck's software I got the mentioned issue directly.

**Comment by GeekyEggo** [comment]
If you're happy to, could you upload one of the MP3s that isn't working to this ticket?

**Comment by WhatIsGetHub** [comment]
I tried to, but Github doesn't let me upload MP3s with the message "We don't support that file type."

**Comment by GeekyEggo** [comment]
> I tried to, but Github doesn't let me upload MP3s with the message "We don't support that file type."

Try adding the MP3 to a ZIP file, and then uploading that. 🤞

**Comment by WhatIsGetHub** [comment]
Hello again, yesterday I tried to use different online converters to MP3 files, and one of them worked.
Probably one of the converters I used had an encoding that cannot be read. 

But yeah, it's fixed now. Thank you for your precious time and your lovely plugin, wish you all luck !
