### ISSUE TITLE
set app audio device

### ISSUE THREAD

**Issue by keykeykeeks** [GeekyEggo/SoundDeck#123]
so is this to set a specific app to a specific audio device? if so im not seeing where to do this at. it just shows froeground and by name and then the audio device. but im not aper to select an app.

**Comment by GeekyEggo** [comment]
Hey @keykeykeeks, you've understood correctly; the text input allows you to specify the application, e.g. "chrome". Sadly, this isn't very intuitive, so in an attempt to improve this, the [latest beta](https://github.com/GeekyEggo/SoundDeck/raw/main/dist/com.geekyeggo.sounddeck.streamDeckPlugin) provides a drop down of available applications. 🙌

**Comment by GeekyEggo** [comment]
No problems, let me know how you get on with the beta version 👍
