### ISSUE TITLE
Set Audio Device Volume No Longer Targets Specific Device

### ISSUE THREAD

**Issue by bjs169** [GeekyEggo/SoundDeck#126]
When using the Set Audio Device Volume action and using the Increase / Decrease the action acts only upon the default audio device irrespective of which audio device is selected in the Audio Device drop down. 

Stream Deck+ Firmware v2.0.3.2
Stream Deck Software v6.2.1.18825
Sound Deck v3.7.2

I have had this setup for a couple months and it was working fine. It only recently broke. I keep up-to-date on both Windows and Stream Deck updates, so it could be either that broke it.

**Comment by bjs169** [comment]
So, rolling back to Stream Deck Software v6.2.0.18816 fixed the issue.

**Comment by GeekyEggo** [comment]
Hey @bjs169, I appreciate you raising a ticket, this wasn’t on my radar. I’ll have a look into it and get back to you.

If you did want to use the latest version of Stream Deck, you could try the [latest Sound Deck beta](https://github.com/GeekyEggo/SoundDeck/raw/main/dist/com.geekyeggo.sounddeck.streamDeckPlugin) which includes general bug fixes.🤞

**Comment by GeekyEggo** [comment]
One follow-up question; would it be possible to get the specific version of Windows you’re using?

**Comment by GeekyEggo** [comment]
Hey @bjs169 I've ran some tests with the latest version of Stream Deck, using the latest version of Sound Deck beta, and everything appears to be working okay; let me know if the latest version of the beta fixes things for you. 😄

**Comment by bjs169** [comment]
*	Windows 11 Pro
*	22H2 
*	Build 22621.1848

 

Thanks,

Brian

**Comment by bjs169** [comment]
> Hey @bjs169 I've ran some tests with the latest version of Stream Deck, using the latest version of Sound Deck beta, and everything appears to be working okay; let me know if the latest version of the beta fixes things for you. 😄

I have been using the beta side-by-side with the release code so I could have dial support. It too was having issues for me. I just updated to SD 6.3 and all is good now. Maybe it was a transient issue, but it did survive a reboot for me. In any case, I think this can be closed.

**Comment by GeekyEggo** [comment]
Glad to hear things are working on 6.3; if you notice anything changes, or functionality isn’t as you’d expect, please feel free to post here and we can investigate further.
