### ISSUE TITLE
time gap between mp3 recordings

### ISSUE THREAD

**Issue by Michael-36** [GeekyEggo/SoundDeck#17]
Hi,
I'm Michael and I use the Elgato Stream Deck with your plugin "Sound Desk". The plugin works really well and I am very happy with it.

I have a question about what I can do to make better use of it:  

My problem is this:
I am recording several MP3 files. Each recording takes about 20 minutes. When I stop the first recording and immediately start the recording of the second file, everything seems to be fine. The Stream Desk shows the correct status with the small symbols.

But: The second recording is missing the first 15 seconds. 
It seems to me that after stopping the first recording, the plugin encodes the this recording into mp3 and then saves the file. This process probably takes about 15 seconds. After this has finished the second recording will be started.

Is there a possibility for me to record several mp3 files without a time gap in between?

**Comment by GeekyEggo** [comment]
Hey @Michael-36, thanks for posing your question; this is definitely an edge case but let's see what we can do to get to the root of the problem.

You mentioned that encoding can take take a few seconds, approximately the same as the difference in recordings. Would it be possible for you to test your scenario with MP3 encoding turned off? If the problem persists, we have narrowed it down one-step.

I will do some investigation into the writing of the files to determine what can be streamlined to try and mitigate the gap.

**Comment by Michael-36** [comment]
Hi @GeekyEggo,
I have tested the recording MP3 encoding turned off:
Then the gap is really small. About one second, which would be fine for me.

**Comment by GeekyEggo** [comment]
@Michael-36 I'm sorry to say that due to time restraints I don't have any plans of fixing this in the foreseeable future; if you're encountering this problem, a possible workaround could be to have 2 separate actions, which you stop/start interchangeably. Less than ideal, but might help. Again, my apologies. :)
