### ISSUE TITLE
feature request push to talk key

### ISSUE THREAD

**Issue by RonnieBlaze** [GeekyEggo/SoundDeck#18]
I use push to talk in a lot of games, it would be nice to be able to set a push to talk key, so it could be "held" while the sound clip is playing.

**Comment by GeekyEggo** [comment]
Hi @RonnieBlaze, key-bindings isn't something planned for SoundDeck at this stage, however you may be able to achieve what you're looking to do by using SuperMacro (a plug-in by BarRaider) and SoundDeck combined in a Multi-action.
