### ISSUE TITLE
Play Audio - Play from Folder

### ISSUE THREAD

**Issue by finnsea** [GeekyEggo/SoundDeck#25]
For the Play Audio action, it would be awesome if we could just point it at a directory and play through audio files in that directory, instead of adding files in individually. This way, when adding new tracks to a playlist, we wouldn't need to go update the action in Stream Deck.

**Comment by finnsea** [comment]
Awesome. If I get some free time this weekend I might play around with getting it added in as well and make a PR for ya. Thanks!

**Comment by GeekyEggo** [comment]
@finnsea no updates on this yet sadly, however as there is a growing interest I have created #39 to centralize all discussion for a new action.
