### ISSUE TITLE
Please add a global Stop 

### ISSUE THREAD

**Issue by Kappinski** [GeekyEggo/SoundDeck#3]
Finally someone who adds a playlist <3 Thank you.
But what I need is a "Stop button" that stops all playing tracks from Sound Deck. To simply push the same button again is not an option for me as I use a multi action that is a collection of global stops for all the other audio stuff happening.
Sound Deck would integrate perfectly with that option on a separate button.

**Comment by GeekyEggo** [comment]
[issue3_rc1.zip](https://github.com/GeekyEggo/SoundDeck/files/3748056/issue3_rc1.zip)
