### ISSUE TITLE
SoundDeck Play Audio: Long press resets play next / cooldown?

### ISSUE THREAD

**Issue by ryantheleach** [GeekyEggo/SoundDeck#30]
I have a series of sound effects that only make sense in close context, that play after one another.

I need an easy way to 'reset' the button for the next time I do the bit/gag.

What would be ideal, is an option for a cooldown, e.g. if it's been longer then a minute or something, reset to the start when i hit the button again.

elsewise, longpressing the button could force the first track to play?

**Comment by GeekyEggo** [comment]
I like the idea of long-press, although I'm wondering if this could be solved by introducing a new [`Action` option](https://github.com/GeekyEggo/SoundDeck/wiki/Play-Audio). Currently there is `Loop All / Stop Reset` option which starts from the first audio clip, and continuously loops the playlist of audio clips until it is pressed for a 2nd time. Pressing the button for a 3rd time starts the continuous loop again from the first audio clip.

Would the option to have a "Play All / Stop (Reset)" work? i.e. Your first press would play all of the clips from the first, with an optional 2nd press stopping the clips and resetting the current to the first?

**Comment by ryantheleach** [comment]
Not for my usecase, no.

I need it to play a sequence, on cue, with some option to reset it when I want.

**Comment by GeekyEggo** [comment]
Okay, a couple of questions;

1. When playing the sequence, do all clips get played?
2. After playing the sequence, would you prefer if it reset _every_ time?

**Comment by ryantheleach** [comment]
Sorry my last reply was so brief, I was quickly replying on mobile.

Essentially, What I currently use Sound Deck is for the following:

Have a sequence of short sound fx tracks, (increasing in pitch) to add emphasis to a bullet point.

I currently have 10, as I usually never need that many. (ignite1-10.mp3)

However, it means I can only use the [bit (definition 2b)](https://www.learnersdictionary.com/definition/bit) once per stream, and need to restart my pc or streamdeck somehow to reset the order.

---
e.g. for a comic bit about selling a car:

"You want to buy this car, because:"

"It can fit 6 clowns" `<hits button, ignite1.mp3 plays to completion>`

"It has all 3 wheels" show missing wheel `<hits button, ignite2.mp3 plays to completion>`

"It can drive straight" show car hitting tree `<hits button, ignite3.mp3 plays to completion>`

Then maybe 30m later, do the same 'gag' but with something else that needs emphasis, needs the sound effects to start from ignite1.mp3 again. (or else they get awkwardly high pitched, same could be done if they were the spoken numbers 1-10)

---

So because it's impossible to predict how much I can improv on the fly, I need it to be a dynamic amount of tracks, played at the appropriate cue point. So it needs to be able to reset (somehow, dynamically)

You can see with the above explanation (I hope) that having it automatically reset in some fashion would prevent mistakes, but it would be fairly easy to get into the muscle memory of doing a long press to reset, either not playing the sound and doing it after the last bit, or before the next. or by combining it with playing the first track.

I hope you (and others) could see the utility of having some method of resetting the tracks, and my proposal of a long-press was intended to be a compromise to make it more useful universally across the various actions.

**Comment by GeekyEggo** [comment]
@ryantheleach I appreciate your detailed response, your desired feature is much clearer now. I had plans of introducing long-press amongst other actions, so this is definitely something I'm interested in achieving. I'll give it some thought and update here in a few days.

**Comment by GeekyEggo** [comment]
Temporarily removing milestone to enable adding support for #42.
