### ISSUE TITLE
Debugging and getting started for SoundDeck

### ISSUE THREAD

**Issue by ryantheleach** [GeekyEggo/SoundDeck#31]
I know C# & Type/Javascript, however due to jumping in and out of multiple community projects, I don't have a lot of experience in any specific tool for initially setting up a repository.

I tried reading over the SharkDeck instructions to try to work out how to fork and jump into SoundDeck development, but didn't have a lot of luck in setting up the build / debug environment.

I'm sure I could spend a few hours dicking about and getting it working, but it'd help me and others if there was a simple walkthrough on how to get started.

This is the error I'm currently getting.

![image](https://user-images.githubusercontent.com/141554/112622824-7d586a00-8e7b-11eb-9014-4667571f3c37.png)

![image](https://user-images.githubusercontent.com/141554/112623103-d6280280-8e7b-11eb-8792-c46a59b05174.png)

**Comment by GeekyEggo** [comment]
@ryantheleach it's odd that `SoundDeck.Plugin.Windows` couldn't be loaded. Have all NuGet packages been restored? SoundDeck has few dependencies, namely NAudio and SharpDeck. The overall structure

- SoundDeck.Core and SoundDeck.Plugin are .NET Standard libraries.
- SoundDeck.Plugin.Windows is a .NET Framework WPF app.

From recent attempts to create a GitHub action, I realised that I'm also referencing a local privacy repository for the property inspector; for this reason I'm sorry to say it's currently impossible to generate this anywhere else. I do have plans of changing this which would make it possible to contribute!
