### ISSUE TITLE
Ogg Audio Support

### ISSUE THREAD

**Issue by ryantheleach** [GeekyEggo/SoundDeck#33]
Please add support for the Ogg Audio format, NAudio appears to support it. <3

**Comment by GeekyEggo** [comment]
@ryantheleach this is now available as part of a separate branch; it would be great if you could download it, have a play, and let me know if you experience any problems.
https://github.com/GeekyEggo/SoundDeck/raw/33-ogg/dist/com.geekyeggo.sounddeck.streamDeckPlugin

**Comment by ryantheleach** [comment]
I'll try it today, thanks

**Comment by ryantheleach** [comment]
Running the file as-is without removing the old one resulted in existing (Sampler Action) buttons giving 'alerts' when pressed.

restarting streamdeck did not fix this.

Opening task manager revealed many many SoundDeck instances installed (probably from my earlier testing of my own streamdeck plugin, it appears that the (previous) version of SoundDeck does not close when StreamDeck is restarted, or is not being opened as a child process of StreamDeck correctly)
![image](https://user-images.githubusercontent.com/141554/113519824-db005b00-95cd-11eb-824a-f2b6afbda357.png)

Killing these now in task manager.

re-opening the plugin file you attached.

Sampler buttons still broken.

Existing sound effect buttons work fine.

New ogg support works for play sound effect button playlists.

**Comment by ryantheleach** [comment]
So basically, 
1. Ogg support works.
**2. Sampler buttons don't upgrade cleanly in this version.** but still work.
3. SoundDeck no longer leaves background processes running in **this** new version.

**Comment by GeekyEggo** [comment]
Can you elaborate on the Samplers not upgrading cleanly?

For local development I'd recommend using the `npm run stop` command; this is a helper script within the `package.json` file that kills both the Stream Deck, and the Sound Deck executable process tree.

**Comment by ryantheleach** [comment]
I'd been using fritzandfriends streamdecktoolkit, but thanks.

The Samplers were pre-existing samplers, but they started working at one point, not sure if it was the multiple sounddeck's that I killed, or creating a new sampler someone re-inited them.

I don't have a backup, nor 100% knowledge which version I was using before testing this, so I apologise how awkward it will be to recreate it, and hope that it's a non issue / complicated with the other stuff I was doing.

**Comment by GeekyEggo** [comment]
I've attempted to replicate the sampler issues by;
1. Downgrading to the current version in the store.
2. Creating a sampler
3. Installing the beta

I haven't been able to replicate any issues, and tested with multiple scenarios; one key change in this beta is the added "Default" devices, although this seemed to be okay. I'll be merging this branch back into `main` soon.

**Comment by GeekyEggo** [comment]
Looking at the [ `NAudio.Wave.AudioFileReader`](https://github.com/naudio/NAudio/blob/fb35ce8367f30b8bc5ea84e7d2529e172cf4c381/NAudio/AudioFileReader.cs#L60) class it appears that `aif[f]` format is also supported natively.
