### ISSUE TITLE
Not recording any sound

### ISSUE THREAD

**Issue by DanyRamdas** [GeekyEggo/SoundDeck#34]
Hi what ever source I pick there is no recording off any sounds.

There are files but only 58 bytes (58 bytes) big.

Could you help me?

**Comment by GeekyEggo** [comment]
Hi Dany, so we can get to the root of the problem I'll need to know a little more about your setup;

- What action are you attempting to record with?
- Is the capture device a Recording or Playback device?
- Is the Output Path a local drive?
- Is Encode To MP3 or Normalize Volume checked?

**Comment by DanyRamdas** [comment]
Hi,

    What action are you attempting to record with?
    Clip Audio
    Is the capture device a Recording or Playback device?
    Playback device
    Is the Output Path a local drive?
    Yes
    Is Encode To MP3 or Normalize Volume checked?
    Yes, I have tried both options.
    
    The application that I am trying to record from is discord.
    Thus I am recording my playback device.

**Comment by GeekyEggo** [comment]
Okay, and one more;
- In Discord, under "Voice & Video" settings, does the Output Device match the action's Capture Device?

**Comment by DanyRamdas** [comment]
Your tip had helped. Now it is working.

Can I ask how the sound is recorded? Is it actively recording continuously my chosen audio playback device?
I ask this out an privacy stand point. Also is it possible to get access to that file If I had bad intentions.

**Comment by GeekyEggo** [comment]
Great to hear, I'm glad it's all working.

> Can I ask how the sound is recorded? Is it actively recording continuously my chosen audio playback device?

That's correct; it continually records the chosen capture device and stores that audio in memory. It only maintains the last x seconds of audio, as defined by the duration drop down.

> I ask this out an privacy stand point. Also is it possible to get access to that file If I had bad intentions.

All recordings are local to the user's machine, and not accessible by me.

- Clip Audio, stores the audio in memory, and then upon pressing the action writes it to a file.
- Record Audio and Sampler write directly to the file.
