### ISSUE TITLE
Cannot change audio device back to default

### ISSUE THREAD

**Issue by arcanatigris** [GeekyEggo/SoundDeck#35]
The default audio device is not available in the audio device list

Would be useful if incase wanna switch from a virtual output to your current default audio device

**Comment by GeekyEggo** [comment]
Hi @arcanatigris, the option for default devices has been added as part of #28, but hasn't yet been released. If you'd like, I'd be more than happy to send you a beta version that includes the changes?

**Comment by GeekyEggo** [comment]
Closing as inactive.
