### ISSUE TITLE
Play first file in folder

### ISSUE THREAD

**Issue by NadirBourazza** [GeekyEggo/SoundDeck#38]
Hi, 
Just recently got SoundDeck and I think it's great, 
I was wondering would it be possible to add functionality to point the play sound to one folder and always play the latest file. The reason I think this feature would be great is so that we can couple it with Clipping audio. We would be able to clip the audio and play back the latest clip to friends, etc.

**Comment by GeekyEggo** [comment]
Hey @NadirBourazza, this is a great suggestion, and one that I think could easily be added to the new "play folder" action. As there are other issues discussing this, I've created a new issue #39, aimed at centralizing the conversation. I'll be sure to post any updates!
