### ISSUE TITLE
Please add a volume slider

### ISSUE THREAD

**Issue by Kappinski** [GeekyEggo/SoundDeck#4]
Please add a volume slider. I want to set the volume of the tracks before the audio is sent to the Audio Device.

**Comment by systemNEO** [comment]
Hi there,

currently version 1.0.0 is available at Elgato Actions. Do you have a plan for releasing 1.1.0 (with advanced order features for play) and the volume slider?

Is there a workaround to adjust the volume by another way?

Best
Hape

**Comment by GeekyEggo** [comment]
@Kappinski and @systemNEO this will shortly be ready for testing if you're interested? I know it's been a while 😅
