### ISSUE TITLE
Cant use pluggin at all

### ISSUE THREAD

**Issue by Kimmno** [GeekyEggo/SoundDeck#44]
Anytime I record something it gets deleted as soon as I end the recording. the file turns into a .tmp file rather I use the "encode to mp3" or not then just disappears. After a few attempt the "capture device" drop down goes blank and then I'm unable to use the drop down at all to select a capture device. I am completely unable to use the clip audio feature. when I press the button I just get a yellow caution sign on my stream deck. I'm running windows 10 . I just got a stream deck today and would really love to have the audio clipping function thanks!

**Comment by GeekyEggo** [comment]
Hey @Kimmno, sorry you’re having problems with Sound Deck; the drop down not populating is likely a result of the plug-in crashing, which might be happening as a result of failing to encode to MP3.

You’re the second person to report an issue with encoding this week, so I’m going to look into changing how encoding works - I’ll update you here when something is available.

In the meantime, are you able to successfully use Sound Deck if you uncheck the option “Encode to MP3”?

**Comment by Kimmno** [comment]
Thanks! and no it does the same thing if I have the encode to mp3 checked or not.

**Comment by GeekyEggo** [comment]
That's unusual; if you navigate to `%AppData%\Elgato\StreamDeck\logs\` in Windows explorer, are there any files named `com.geekyeggo.sounddeck.log`?

**Comment by Kimmno** [comment]
i have 4. they are
com.geekyeggo.sounddeck0
com.geekyeggo.sounddeck1
com.geekyeggo.sounddeck2
com.geekyeggo.sounddeck3

but no com.geekyeggo.sounddeck.log

**Comment by GeekyEggo** [comment]
They’re the ones; could you zip them and add them to this issue? They’ll hopefully offer some insight into what’s going wrong.

**Comment by Kimmno** [comment]
[logs.zip](https://github.com/GeekyEggo/SoundDeck/files/6897448/logs.zip)

**Comment by GeekyEggo** [comment]
@Kimmno, the latest beta version, [v2.1.4](https://github.com/GeekyEggo/SoundDeck/raw/46-AppAudioInterop/dist/com.geekyeggo.sounddeck.streamDeckPlugin) includes much more logging. If you continue to encounter problems, please upload the log files, located at `%appdata%\Elgato\StreamDeck\Plugins\com.geekyeggo.sounddeck.sdPlugin\logs\sounddeck.log`, and I will take a further look.

**Comment by GeekyEggo** [comment]
Closing to inactivity, but please feel free to comment and if you wish to discuss things further.
