### ISSUE TITLE
Add option to reset to default device

### ISSUE THREAD

**Issue by D0nky** [GeekyEggo/SoundDeck#48]
This plug-in is life changer, but it could be even better with a "default windows device" option in the device list.
With few different device, it could be a pain to manage few apps, it would be useful to be able to reset to default device.

**Comment by GeekyEggo** [comment]
Hey @D0nky, I appreciate the kind words, and you taking the time to provide feedback. Some actions within Sound Deck allow for the default device to be selected from the devices list; could I ask which actions you're particularly interested in? I'd like to expand this option further, so it would be great to understand the areas that would benefit you.

| Action | Playback Device | Recording Device
| - | - | - |
| Clip Audio | ❌ | ❌ |
| Play Audio | ✔ | N/A |
| Record Audio | ❌ | ❌ |
| Sampler (Recording) | ❌ | ❌ |
| Sampler (Playback) | ✔ | N/A |
| Set App Audio Device | ✔ (default communication not supported)  | N/A |

**Comment by D0nky** [comment]
Oh i forgot to specify the action, sorry. I was talking about "Set App Audio Device".
It seems that i'm supposed to select default playback device, but i can't see it in the list.
![image](https://user-images.githubusercontent.com/29195994/137637994-1ba197ee-44af-40df-9cb8-e5a66cbede78.png)

**Comment by GeekyEggo** [comment]
So, it would appear that I’m well overdue a new release; these changes were added in April of this year, i.e. a long time ago, however… the last release on the Elgato store was February. 😅

You can download the most up to date beta directly from [here](https://github.com/GeekyEggo/SoundDeck/blob/main/dist/com.geekyeggo.sounddeck.streamDeckPlugin?raw=true) to gain access to this functionality now.
