### ISSUE TITLE
Windows 11 Dropdown not available

### ISSUE THREAD

**Issue by Loco360** [GeekyEggo/SoundDeck#51]
It is not possible to see the dropdown with windows 11. Tried deinstalling and reinstalling. The devices are not shown in the dropdown...

![image](https://user-images.githubusercontent.com/47069874/139645542-8bd6e294-28ab-4856-ae4a-0e9ee546f182.png)

**Comment by rikward** [comment]
I'm having this issue as well.  I have other plugins which also list audio devices (such as BarRaider's Audio Meter) which continue to work under Win11.

I cloned the plugin to have a look to see if I could fix this myself, but unfortunately the _react-sharpdeck_ library doesn't seem to be available, which means I can't (easily) build the Solution.

**Comment by GeekyEggo** [comment]
Hey @Loco360, sadly this is a known issue which requires low-level understanding of Windows 11; sadly I'm unable to debug Windows 11 issues atm, but I'm working on having access to an environment to hopefully find a solution.

@rikward this stems deeper than just displaying the devices list, as other actions within Sound Deck are working fine on Windows 11. There are interoperability changes to Windows 11 that change how [`IAudioPolicyConfigFactory`](https://github.com/GeekyEggo/SoundDeck/blob/main/src/SoundDeck.Core/Interop/IAudioPolicyConfigFactory.cs) is instantiated, and thus are resulting in an invalid cast of the COM object.

I'll re-locate the react-sharpdeck library to allow for forking.

**Comment by GeekyEggo** [comment]
Moving this conversation to #52 to track this better.

**Comment by taprootwizard** [comment]
Hi, while I've seen this has been solved in another thread, it is currently not working (maybe an update broke it?). I recently installed Sound Deck on a Windows 11 PC (running latest version) and no sound devices are showing up when I click on the dropdown
