### ISSUE TITLE
Stop Audio button doesn't stop audio for Play All/Stop, Loop All/Stop and Loop All/Stop (Reset) actions

### ISSUE THREAD

**Issue by mansman12** [GeekyEggo/SoundDeck#59]
For actions like Play All/Stop, Loop All/Stop and Loop All/Stop (Reset), the Stop Audio button just moves on to the next track in the queue rather than ending the audio.

Is this intended functionality?

**Comment by GeekyEggo** [comment]
@mansman12 I've tested this with the current release, and I'm able to replicate the problem you're encountering. This isn't how the stop audio action should be functioning, my apologies.

As part of #60 I've made some changes to stopping audio; would you mind testing a beta release ([download link](https://github.com/GeekyEggo/SoundDeck/raw/60-overlap/dist/com.geekyeggo.sounddeck.streamDeckPlugin)) to see if this fixes the problem for you please.

**Comment by mansman12** [comment]
@GeekyEggo I've tested the beta release and can confirm that the stop audio action now stops all audio from the play all and loop all actions.
