### ISSUE TITLE
Switching Back to source Profile/Page in Stream Deck Stops Audio

### ISSUE THREAD

**Issue by mansman12** [GeekyEggo/SoundDeck#65]
As above, to re-create the issue:

1. Create two profiles or pages (A and B) and add a play action (any action will work) on profile/page A with any music.
2. Use the play action button and navigate to profile/page B (via an assigned Stream Deck button or via the desktop app)
3. Navigate back to profile/page A
4. Audio ends

I can confirm that this happens in both the current release and the beta version linked by @GeekyEggo in Issue #59

**Comment by mansman12** [comment]
Issue persisted for any actions created using the current version. By deleting and re-creating the action the issue looks to be solved in the following two cases:

- Action on a profile/page
- Action as part of a Stream Deck Multi-Action button

Thanks for taking a look at it!

**Comment by mansman12** [comment]
Related to the above (have yet to test the current version), 3.5.3-beta seems to have an issue where the volume set for individual tracks doesn't persist.

Can be re-created by just changing the volume of a track assigned to an action and then clicking the gear twice (always reverts to 75).

**Comment by GeekyEggo** [comment]
That's what I get for rushing, d'oh! [3.5.4-beta](https://github.com/GeekyEggo/SoundDeck/raw/65-action-disposal/dist/com.geekyeggo.sounddeck.streamDeckPlugin) should resolve that!

**Comment by mansman12** [comment]
No worries! Tested 3.5.4-beta and can confirm that the switching bug and volume bug are both fixed in this version.

**Comment by GeekyEggo** [comment]
Great news, thanks @mansman12.
