### ISSUE TITLE
Looping Samples?

### ISSUE THREAD

**Issue by moonlightonion** [GeekyEggo/SoundDeck#67]
It would be awesome if there was a way to loop samples captured in the sampler!

**Comment by GeekyEggo** [comment]
Hey @moonlightonion, hopefully what you're looking for is already supported in Sound Deck;

1. Select the sampler action you want to loop.
2. Scroll to the bottom of the settings window.
3. For the "Action" option, select "Loop / Stop".

With this option selected, pressing the button once will continuously loop the sample. Pressing the button again will stop the loop.

**Comment by moonlightonion** [comment]
Thank you so much for letting me know this, sorry to take up your time!

**Comment by GeekyEggo** [comment]
Honestly no need for apologies, I’m happy it solved your problem. 😄 If you have any suggestions please don’t hesitate to post them.
