### ISSUE TITLE
PLEASE ADD MAC SUPPORT

### ISSUE THREAD

**Issue by Frankiemagic13** [GeekyEggo/SoundDeck#68]
I ech virtual shows and work production and but im on a mac can you please add support for macthank you so much

**Comment by GeekyEggo** [comment]
Hey @Frankiemagic13, I would absolutely love to provide Mac support, but sadly it would require a lot of changes. The plug-in is designed with Mac in mind, but as I'm unable to test any efforts, i.e. I develop on Windows, this would be too difficult at this stage. My apologies.
