### ISSUE TITLE
VoiceMod and Mic Support for Sampler

### ISSUE THREAD

**Issue by Barweezle** [GeekyEggo/SoundDeck#72]
@GeekyEggo  I have personally been loving the Sound Deck plug-in for Elgato... Only thing is I would love to be able to choose different Mic choices as an Output. I currently use voicemod for most and getting the sample to play through Mic would be fantastic! Or to set up Multiple outputs at once so it could be possible to send out a sample through  mic > voicemod > discord. I personally utilize the Elgato wave 3 software and can't find a way to have samples play out to my stream and the in game voice chat at the same time all while I can hear it too... My only work around was to force all through VM and its a hassle and I cant personally hear the samples to react as my chat does. I  have tried selecting VM as an output for the SFX tab in the W3 software and its very poopy and distorted. The audio clip plays fine until I setting it to a setting where everyone could hear it. I know it may be confusing to understand. but I'd love to give in-site and hope to see this plug in be the best it can be.

thank you for reading and hopefully understanding!
weezle

**Comment by GeekyEggo** [comment]
Hey @Barweezle, thanks for the kind words, and the detailed description.

If I’m understanding correctly, you’d like to have a way of playing back a sampler that yourself and your stream can hear it?

Although this could definitely be achieved with multiple output sources in Sound Deck (ref #6), I think we might be able to achieve this with your current setup given the Wave:3.

In Wave Link, are there any inputs that are shared amongst the Monitor Mix and Stream Mix? Assigning the “Playback Device” in the sampler settings to one of these shared inputs should hopefully give the desired effect.

I’m not overly familiar with the Wave Link software, so apologies in advance if this doesn’t help. I did also discover an article about distortion issues on the Elgato website that might also help, [Wave Link - Audio Input Or Output Distorted](https://help.elgato.com/hc/en-us/articles/4416633321485-Wave-Link-Audio-Input-Or-Output-Distorted).

**Comment by Barweezle** [comment]
Thank you for the very quick response. I'm going to do a bit of trouble
shooting with the new information. As of right now the shared input and
output is only the Voicemod software. Setting the "Playback Device" to
voicemod sends the sampled sound through my mic. In which my Party chat can
be heard as well as the stream but, I cannot. I didn't see the Multiple
Output Sources ref #6 section. I appreciate the help. If any other
questions are alright to ask for assistance or a question, may I reach out
in the future?

Thank you again for your time!

**Comment by GeekyEggo** [comment]
> As of right now the shared input and
output is only the Voicemod software

Hmm, I’m a little surprised by this; which input device are you using for things like game audio or stream alerts?

> If any other questions are alright to ask for assistance or a question, may I reach out
in the future?

Of course! We’ll find a solution.

**Comment by Barweezle** [comment]
As of right now, My system settings are set to
Output  "Wave Link System" - Told to assign when setting up Wave 3 mic.
Input - "Wave Link Microphone"

After setting those as the main Input and output. I have to set Voicemod to
Input "Wave Link Microphone" and the Output is directed to the "Wave Link
SFX" section of the software.
     The Wave Software has built in splitters to send my outputs to
different channels and the option to mute to either stream output or my
headset output. I can also set each app individually to a different output
section.

I have also set my OBS softwares to the Output as "Wave Link System" and
Input at "Wave Link Microphone"
. I've tried many combos of mic choices EX Wave mic, Woicemode, etc and I
can't brain my way through it yet.

I hope this helps a bit. I am not very good at explaining through message
etc

**Comment by GeekyEggo** [comment]
Your configuration sounds correct.

Would I be correct in saying Wave Link adds audio devices similar to the GoXLR? (press `Win`+`R`, and enter `control.exe /name Microsoft.Sound`).

![image](https://user-images.githubusercontent.com/1429781/152852028-88fef65d-404e-4c21-8ca7-44ada2625c17.png)

If so, it should just be a case of routing the devices to the correct channels. In the context of a GoXLR, there is a "Sample" input device which I can route to "Chat Mic" and "Headphones". This allows anything played to that device to be broadcast to chat and my headphones. Optionally I could also add this to "Broadcast Stream Mix" for my stream. The routing table looks like this:

![image](https://user-images.githubusercontent.com/1429781/152852953-bdcbbceb-8bc7-4ea3-9a04-6fd150d10f56.png)

With this setup, I'm able to select "Sample" as the playback device in the sampler settings so that myself, and my stream can hear me.

![image](https://user-images.githubusercontent.com/1429781/152853330-064a5d37-0306-45c5-a239-44b1a23f6cbe.png)

**Comment by GeekyEggo** [comment]
Hey @Barweezle I’m going to close this as it’s gone quiet; I’m happy to discuss it further if needed though.

**Comment by Barweezle** [comment]
I'm so sorry for the quietness. I was very swamped and busy. Dealing with
OBS crashes and so many other issues I haven't been able to figure out the
fix yet. wave link doesn't have a "sampler" output sadly to choose from and
a work around is rough. I would need to definitely screenshot and send
images of my set up after this OBS update fix due to everything being
broken. I'm sorry for the inconveniences. I personally think "multiple
output" plug in would help the best for this.

I appreciate your time!
Thank you again
Weezle
