### ISSUE TITLE
Actions missing

### ISSUE THREAD

**Issue by wizard04wsu** [GeekyEggo/SoundDeck#74]
I don't see all 11 actions in the list. These are not available:

- App Media Controls
- Set App Volume
- Set Default Audio Device
- Set Audio Device Volume

I have Sound Deck v3.0.2 installed in Stream Deck v5.2.1 using device CORSAIR G-Keys v4.20.169.

![image](https://user-images.githubusercontent.com/695638/159112744-d65c2b0b-7ba3-4ae6-9792-7eb836704aa7.png)

**Comment by GeekyEggo** [comment]
All actions are available within the beta, which isn't yet on the Elgato Store, but can be downloaded directly from [here](https://github.com/GeekyEggo/SoundDeck/raw/main/dist/com.geekyeggo.sounddeck.streamDeckPlugin). Please let me know if this fixes the issue.
