### ISSUE TITLE
Add play/fade as action to play audio

### ISSUE THREAD

**Issue by thedanholt** [GeekyEggo/SoundDeck#78]
Play/fade would allow a second press of the button to fade out the audio over say 1, 2 or 3 seconds. Currently closest option is play/stop but this stops the audio sharply rather than subtly.

![image](https://user-images.githubusercontent.com/77852497/160864023-b6defc48-c4f4-415a-acbe-85d7a8adbb08.png)

**Comment by GeekyEggo** [comment]
Hey @thedanholt, thanks for the feedback; fading has been suggest previously, but this approaches it in a different way, i.e. fading / blending tracks, which I quite like. At the moment I don't have much time to invest in new features, but hopefully when time becomes available, I'll see what I can do. 👍

**Comment by GeekyEggo** [comment]
As part of triaging issues, I plan to consolidate these changes as part of #41.
