### ISSUE TITLE
Toggle Loop // Loop Per File setting

### ISSUE THREAD

**Issue by QuantaCat** [GeekyEggo/SoundDeck#80]
I would like a feature that lets you toggle a loop on a currently activated Play Audio node, ie. switches it from Loop/Stop or Loop All/Stop to Play/Stop, and vice versa. It would let the currently looped sound end, or set loop, as the node is otherwise set up. 

Alternatively (or additionally), files you load into the playlist could have their own Loop/Play Once setting, meaning they would either play once or loop on reaching the end of that particular file, and would continue looping until you use a Toggle Loop function, or on tapping the button again. 

Use case: you want to transition to a different background music, or you are approaching the end of a stream/session/performance, and let the playlist progress naturally, for example if it is set up with Intro-Loop-Outro files in a playlist.

**Comment by GeekyEggo** [comment]
Hi @QuantaCat, my apologies for not responding to this sooner! Currently there aren't any plans to allow looping-per-file; I fear this could cause the settings window to become quite complex. This may change in the future, but as an interim solution, you may be able to achieve something using a combination of multi-actions, and "Stop Audio" action.
