### ISSUE TITLE
Set app audio device not switching over to other audio device

### ISSUE THREAD

**Issue by kekev2001** [GeekyEggo/SoundDeck#81]
if  i setup the Proces by name to like discord.exe it is not switching over to other playback device

**Comment by GeekyEggo** [comment]
Are you trying to control the notification audio, or the voice chat audio? As Discord controls the voice chat audio within the application it won't be possible to change that using the action. If you wish to change the notification output this can be achieved by setting the process name to "discord" or "discord.exe", and then the desired device.

**Comment by kekev2001** [comment]
i want to set the output of discord voicechat sounds and also the notify sounds on a other audio device

**Comment by GeekyEggo** [comment]
### Change Discord Notification Device.
1. Create a "Set App Audio Device" action.
2. Set "Process" to be "By Name", and enter the name "Discord.exe".
3. Set the desired audio device.

### Change Discord Voice Chat Device.
1. In Discord, go to Settings > Voice & Video, and set "Output Device" to "Default".
2. In Stream Deck, create a "Set Default Audio Device".
3. Set the desired audio device.
4. Set "Role" to be "Communication".

**Comment by kekev2001** [comment]
![Schermafbeelding 2022-04-16 202435](https://user-images.githubusercontent.com/56051728/163687010-a68ef554-310d-4b73-aea9-ac85603c0566.png)
![Schermafbeelding 2022-04-16 202542](https://user-images.githubusercontent.com/56051728/163687032-9a460f2a-ecf8-4670-a5a6-4ae7025692aa.png)


when i press this button the audio  ouput device stays here

**Comment by GeekyEggo** [comment]
In Discord, output should be “Default”.

**Comment by kekev2001** [comment]
i did this noting changed

**Comment by GeekyEggo** [comment]
Did you use the “Set Default Audio Device”? The “Set App Audio Device” won’t work for changing voice chat.

**Comment by kekev2001** [comment]
no i need to use the Set app audio device i only want discord on channel 8 and internet browser

**Comment by GeekyEggo** [comment]
Try with the “Set Default Audio Device” and role as “Communication”; other applications should remain unaffected.

**Comment by kekev2001** [comment]
but it will only do discord?

**Comment by GeekyEggo** [comment]
There’s one way to find out, try it. 😄

**Comment by kekev2001** [comment]
> Try with the “Set Default Audio Device” and role as “Communication”; other applications should remain unaffected.

i did this also notings happend
or changed

**Comment by GeekyEggo** [comment]
@kekev2001, I've done some testing and managed to get this working, here's what you'll need to do...
# Discord
- In Discord, the Output device **must** be `Default`.
- When set to `Default`, Discord uses the system's default Communication Device.

![image](https://user-images.githubusercontent.com/1429781/164689657-78fe1b35-1b99-48e9-bb52-827e5e231088.png)

# Sound Deck
- Create a "Set Default Audio Device" action.
- The role **must** be `Communication` only, otherwise all system audio will change.

![image](https://user-images.githubusercontent.com/1429781/164700731-c3ea8fb1-3fac-48cf-ba22-05aa6c7b7451.png)

This will then change the system's default communication device, which will change Discord's voice chat output.

![image](https://user-images.githubusercontent.com/1429781/164700546-261f8d45-35a9-4217-b937-e188e485f1e2.png)

**Comment by kekev2001** [comment]
i just did this only also this dont worked

**Comment by GeekyEggo** [comment]
@kekev2001 could you record a short video showing your Discord voice settings and the Stream Deck action you’re trying with.

**Comment by kekev2001** [comment]
https://we.tl/t-mGK2VAUulF
this is the video

**Comment by GeekyEggo** [comment]
@kekev2001 you're using the wrong action type; to change Discord voice chat you will need to use "Set Default Audio Device", do not use "Set App Audio Device".

**Comment by GeekyEggo** [comment]
@kekev2001 did you manage to get this working?

**Comment by kekev2001** [comment]
> @kekev2001 did you manage to get this working?

not yet is there a other way to get this working

**Comment by GeekyEggo** [comment]
It isn't possible to control the Discord audio (defined in Discord) via the API, AFAIK. Following the instructions listed [above](https://github.com/GeekyEggo/SoundDeck/issues/81#issuecomment-1106372211), i.e. using the "Set Default Audio Device" (and not Set App Audio Device) will work.

**Comment by kekev2001** [comment]
i also tried that notings works do you have discord so that i can show you it
