### ISSUE TITLE
cant select capture device for sampler or record audio

### ISSUE THREAD

**Issue by Juddex** [GeekyEggo/SoundDeck#83]
for some reason when i try to select the capture device, it just shows a grey box, with a yellow border line.

it was working before but now it doesn't seem to work at all even tho i tried uninstalling and reinstalling the plugin.

**Comment by GeekyEggo** [comment]
Hey @Juddex, I believe Windows recently released an update for .NET 4.8, which is what Sound Deck uses as the coding framework; are all available Windows updates installed?

To track down what might be causing the problem, could I ask if there are any entries relating to SoundDeck.exe in event viewer. This can be determined by doing the following:

1. Exit Stream Deck (entirely).
2. Open Stream Deck.
3. Try to select a capture device.
4. Press `Win` + `R`.
5. Enter `eventvwr` and "OK".
6. On the left, select "Windows Logs", "Application".

Hopefully there should be an "Error" entry relating to SoundDeck.exe.

**Comment by Juddex** [comment]
thanks for the reply, i followed the steps and i got this error:

Application: SoundDeck.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFB729C5FC5 (00007FFB72930000) with exit code 80131506.

**Comment by Juddex** [comment]
> Hey @Juddex, I believe Windows recently released an update for .NET 4.8, which is what Sound Deck uses as the coding framework; are all available Windows updates installed?
> 
> To track down what might be causing the problem, could I ask if there are any entries relating to SoundDeck.exe in event viewer. This can be determined by doing the following:
> 
> 1. Exit Stream Deck (entirely).
> 2. Open Stream Deck.
> 3. Try to select a capture device.
> 4. Press `Win` + `R`.
> 5. Enter `eventvwr` and "OK".
> 6. On the left, select "Windows Logs", "Application".
> 
> Hopefully there should be an "Error" entry relating to SoundDeck.exe.

**Comment by Juddex** [comment]
i just checked in device manager, i do believe i have 4.8 net installed, but the elgato software doesnt seem to detect it. 

this is the screenshot from device manager for the net framework setup
![ev](https://user-images.githubusercontent.com/105492375/168422056-6becfb64-5bf8-4af9-8170-15f4f9a63a1b.png)

**Comment by GeekyEggo** [comment]
Your version of .NET looks up to date; the “Release” entry matches the expected current version (I think).

I’ve done a bit of research into the error, and sadly it doesn’t look like an easy thing to identify or fix. Multiple articles are highlighting it’s likely cause is a corruption in memory when running garbage collection; as unlikely as it is, I’d recommend running something like memtest86 to eliminate the possibility of a hardware fault.

Couple of extra questions:
1. Are you able to use _any_ actions within Sound Deck?
2. What actions from Sound Deck do you have on your Stream Deck?

**Comment by Juddex** [comment]
> Your version of .NET looks up to date; the “Release” entry matches the expected current version (I think).
> 
> I’ve done a bit of research into the error, and sadly it doesn’t look like an easy thing to identify or fix. Multiple articles are highlighting it’s likely cause is a corruption in memory when running garbage collection; as unlikely as it is, I’d recommend running something like memtest86 to eliminate the possibility of a hardware fault.
> 
> Couple of extra questions:
> 
> 1. Are you able to use _any_ actions within Sound Deck?
> 2. What actions from Sound Deck do you have on your Stream Deck?

all the audio related device actions work fine

but the action from sampler to stop audio dont work at all

i only have the sampler in sdk for testing purposes when i found out i cant select the capture device

and also what do u mean by "corruption in memory when running garbage collection"

isit like computer ram problem or the elgato software problem

becuz it worked fine before then i uninstalled it becuz i didnt use it that much at that time. but recently when i downloaded back the sampler and play or record actions stopped working

**Comment by GeekyEggo** [comment]
> i only have the sampler in sdk for testing purposes when i found out i cant select the capture device

ah, so the sampler action is in a separate profile? I suspect it may be related to the sampler action specifically; could I ask you to try some scenarios in an attempt to "force" the problem to occur.

## Scenario A

### Setup

1. Create a new profile.
2. Add Sound Deck's "play audio" action (and only this action).
3. Configure the action to play an audio file.
4. Temporarily set the new profile to your default profile.
5. Exit Stream Deck entirely, and re-open it.

### Questions

1. Does the "play audio" action work?
2. If you go to the settings of "play audio" action, is the list of playback devices populated?

## Scenario B

### Setup

1. Add a "sampler" action to the profile created in scenario 1.
2. Setup the sampler action.
4. Exit Stream Deck entirely, and re-open it.

### Questions

1. Does the "play audio" and "sampler" action work?
2. Do their settings load correctly, i.e. the playback and capture device drop downs?

## Scenario C

### Setup

1. Remove the "sampler" action.
2. Exit Stream Deck entirely, and re-open it.
3. Add a "clip audio" action, and set it up.
4. Set its clip duration to be low 15 seconds.
5. Exit Stream Deck entirely, and re-open it.

### Questions

Wait 30 seconds after opening the Stream Deck app.

1. Does the "play audio" and "clip audio" action work?
2. Do their settings load correctly, i.e. the playback and capture device drop downs?

**Comment by Juddex** [comment]
> 

Thank u so much, I'm not at my com atm, but I will try this out when I get back and luk if it fixes the issue :)

**Comment by Juddex** [comment]
@GeekyEggo at first scenario a and b still had the problem but then after scenario C did it!!!! Worked perfectly, no issues at all

just one more qn, can i now go back to my old profile and add the actions ? would they work ?

**Comment by GeekyEggo** [comment]
@Juddex thanks for testing the scenarios! Just to confirm, did scenario C cause the problem, or solve it? 😅 The “clip audio” manages memory differently to others actions.

**Comment by Juddex** [comment]
> @Juddex thanks for testing the scenarios! Just to confirm, did scenario C cause the problem, or solve it? 😅 The “clip audio” manages memory differently to others actions.

@GeekyEggo scenario solved the problem, thanks again a lot :)

**Comment by GeekyEggo** [comment]
Awesome, glad I could help! 🥳 I’m going to close this issue, but if the problem comes back, please post in here and we’ll solve it… again, lol.
