### ISSUE TITLE
Can't see my microphone audio level

### ISSUE THREAD

**Issue by vickec07** [GeekyEggo/SoundDeck#86]
^^

**Comment by GeekyEggo** [comment]
Hi @vickec07, when raising please be descriptive as possible;  

1. Is this a bug, or a feature request?
1. What action does it relate to?
1. Do other audio devices work okay?

Also, if there are any screenshots or videos that help demonstrate the problem, please attach them too.

**Comment by vickec07** [comment]
> 

1. Not a feature, most likely a bug
2. Not sure
3. Other audio devices works fine

**Comment by GeekyEggo** [comment]
You’re going to need to be more descriptive. How did you encounter this bug?

**Comment by GeekyEggo** [comment]
Marking this as closed as there isn’t enough information to identify or replicate a possible problem.
