### ISSUE TITLE
No devices

### ISSUE THREAD

**Issue by schmittyd** [GeekyEggo/SoundDeck#90]
No devices show in `Audio Device`, `Capture Device` or `Playback Device` menus in Stream Deck 6.0 Beta.

**Comment by GeekyEggo** [comment]
Thanks @schmittyd; as noted on the Discord, there are currently breaking changes in the SDK which are under discussion at the moment as to whether they'll become permanent. These SDK changes break a _lot_ of plugins, including those from BarRaider and myself.

I'm going to put this on-hold until we know more from Elgato, apologies for the inconvenience.

**Comment by GeekyEggo** [comment]
This is now fixed in the newer versions of the beta. 🥳
